on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: python3 -m pip install -U pip setuptools wheel
    - run: python3 -m pip install -r requirements.txt
    - run: python3 -m platformio run
