on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        python3 -m venv .venv
        . .venv/bin/activate
        pip install -U pip
        pip install -U setuptools wheel
    - run: |
        . .venv/bin/activate
        pip install -r requirements.txt
    - run: |
        . .venv/bin/activate
        pio run
